---
- name: Install packages
  yum:
    name: docker,docker-distribution,@webserver,ansible
    state: latest

- name: Create htpasswd File
  shell: htpasswd -cBb /etc/docker-distribution/registry/.htpasswd admin {{ registry_pw }}

- name: Create Registry Configuration
  template:
    src: config.yml.j2
    dest: /etc/docker-distribution/registry/config.yml

- name: Create Key
  openssl_privatekey:
    path: /etc/docker-distribution/server.key
    type: RSA
    size: 1024

- name: Create CSR
  openssl_csr:
    path: /tmp/server.csr
    privatekey_path: /etc/docker-distribution/server.key
    common_name: "{{ registry_hostname }}"

- name: Create Self-signed Certificate
  openssl_certificate:
    path: /etc/docker-distribution/server.crt
    privatekey_path: /etc/docker-distribution/server.key
    csr_path: /tmp/server.csr
    provider: selfsigned

- name: Change Key Permissions
  file:
    path: /etc/docker-distribution/server.key
    mode: '0600'

- name: Change SElinux Context of Certificate and Key
  sefcontext:
    target: /etc/docker-distribution/{{ item }}
    setype: cert_t
    state: present
  loop:
  - server.crt
  - server.key
        
- name: Restorcon on Certificate and Key
  command: restorecon -vF /etc/docker-distribution/server.key /etc/docker-distribution/server.crt

- name: Start docker and docker-distribution
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
  - docker
  - docker-distribution
