---
- name: Deploy container registry
  hosts: tag_Type_Docker
  become: yes
  roles:
    - registry
  tasks:
    - name: Fetch Registry Certificate
      fetch:
        src: /etc/docker-distribution/server.crt
        dest: /tmp/server.crt
        flat: yes

- name: Push Container Images to registry
  hosts: localhost
  become: yes
  tasks:
    - name: Install Packages
      yum:
        name: docker,skopeo,docker-python
        state: latest

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create Docker Certificate Directory for Registry
      file:
        path: "/etc/docker/certs.d/{{ registry_hostname }}:5000"
        state: directory

    - name: Copy Registry Certificate into Docker
      copy:
        src: /tmp/server.crt
        dest: "/etc/docker/certs.d/{{ registry_hostname }}:5000/server.crt"
    
    - name: Login to Docker Registry
      docker_login:
        registry: "{{ registry_hostname }}:5000"
        username: admin
        password: "{{ registry_pw }}"

    - name: Push Images to registry
      shell: 'skopeo copy --dest-tls-verify=false dir://data/{{ item.split(" ")[0] }} docker://{{ registry_hostname }}:5000/{{ item.split(" ")[1] }}'
      loop: "{{ lookup('file', 'images').splitlines() }}"

- name: Add Registry Certificate to OCP Nodes
  hosts: tag_Type_OSE_App:tag_Type_OSE_Infra:tag_Type_OSE_Master
  become: yes
  tasks:
    - name: Install Packages
      yum:
        name: docker
        state: latest

    - name: Create Docker Certificate Directory for Registry
      file:
        path: "/etc/docker/certs.d/{{ registry_hostname }}:5000"
        state: directory

    - name: Copy Registry Certificate into Docker
      copy:
        src: /tmp/server.crt
        dest: "/etc/docker/certs.d/{{ registry_hostname }}:5000/server.crt"