---
- name: common services
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - http
    - https
    - ssh

- name: common tcp ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - 1936/tcp
    - 8443/tcp
    - 8444/tcp
    - 9100/tcp
    - 10250/tcp
    - 4789-8053/tcp
    - 9200/tcp
    - 9300/tcp
    - 9090/tcp
    - 53/tcp


- name: common udp ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - 4789-8053/udp
    - 53/udp

- name: common infra-master tcp ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - 2049/tcp
    - 2379/tcp
    - 2380/tcp


- name: common infra-master ud ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - 2049/udp