---
- name: Converge
  hosts: all
  vars:
    iam_policies:
      - name: RH-Master-Node-IAM-Policy-TEST
        description: Red Hat Master Node IAM Policy - Contains EC2 and ELB permissions. - Adrian
        policy:
          Version: '2012-10-17'
          Statement:
          - Action:
            - ec2:DescribeVolume*
            - ec2:CreateVolume
            - ec2:CreateTags
            - ec2:DescribeInstances
            - ec2:AttachVolume
            - ec2:DetachVolume
            - ec2:DeleteVolume
            - ec2:DescribeSubnets
            - ec2:CreateSecurityGroup
            - ec2:DescribeSecurityGroups
            - ec2:DescribeRouteTables
            - ec2:AuthorizeSecurityGroupIngress
            - ec2:RevokeSecurityGroupIngress
            - elasticloadbalancing:DescribeTags
            - elasticloadbalancing:CreateLoadBalancerListeners
            - elasticloadbalancing:ConfigureHealthCheck
            - elasticloadbalancing:DeleteLoadBalancerListeners
            - elasticloadbalancing:RegisterInstancesWithLoadBalancer
            - elasticloadbalancing:DescribeLoadBalancers
            - elasticloadbalancing:CreateLoadBalancer
            - elasticloadbalancing:DeleteLoadBalancer
            - elasticloadbalancing:ModifyLoadBalancerAttributes
            - elasticloadbalancing:DescribeLoadBalancerAttributes
            Resource: "*"
            Effect: Allow
            Sid: '1'
  roles:
    - role: iam-policy
