base_volume:
  device_name: /dev/sda1
  volume_size: 60
  delete_on_termination: yes

servers:

  - tags:
      Name: "{{ vpc_name }}-master-01"
      EnvID: "{{ env_id }}"
      Type: OSE_Master
      Function: OpenShift
      kubernetes.io/cluster/c3ms: owned
    count: 1
    subnet_id: "{{ az_b_subnet_id }}"
    assign_public_ip: no
    image: "{{ ocp_ami }}"
    instance_type: "{{ master_instance_type }}"
    security_groups:
      - "{{ vpc_name }}-ocp-masters"
      - "{{ default_security_group }}"
    iam_profile: "ocp-master-node-iam-role"
    function: "OpenShift"
    volumes:
      - "{{ base_volume }}"
      - device_name: /dev/sdd
        volume_size: 100
        delete_on_termination: yes
      - device_name: /dev/sde
        volume_size: 100
        delete_on_termination: yes

  - tags:
      Name: "{{ vpc_name }}-master-02"
      EnvID: "{{ env_id }}"
      Type: OSE_Master
      Function: OpenShift
      kubernetes.io/cluster/c3ms: owned
    count: 1
    subnet_id: "{{ az_b_subnet_id }}"
    assign_public_ip: no
    image: "{{ ocp_ami }}"
    instance_type: "{{ master_instance_type }}"
    security_groups:
      - "{{ vpc_name }}-ocp-masters"
      - "{{ default_security_group }}"
    iam_profile: "ocp-master-node-iam-role"
    function: "OpenShift"
    volumes:
      - "{{ base_volume }}"
      - device_name: /dev/sdd
        volume_size: 100
        delete_on_termination: yes
      - device_name: /dev/sde
        volume_size: 100
        delete_on_termination: yes

  - tags:
      Name: "{{ vpc_name }}-master-03"
      EnvID: "{{ env_id }}"
      Type: OSE_Master
      Function: OpenShift
      kubernetes.io/cluster/c3ms: owned
    count: 1
    subnet_id: "{{ az_c_subnet_id }}"
    assign_public_ip: no
    image: "{{ ocp_ami }}"
    instance_type: "{{ master_instance_type }}"
    security_groups:
      - "{{ vpc_name }}-ocp-masters"
      - "{{ default_security_group }}"
    iam_profile: "ocp-master-node-iam-role"
    function: "OpenShift"
    volumes:
      - "{{ base_volume }}"
      - device_name: /dev/sdd
        volume_size: 100
        delete_on_termination: yes
      - device_name: /dev/sde
        volume_size: 100
        delete_on_termination: yes

  - tags:
      Name: "{{ vpc_name }}-node-01"
      EnvID: "{{ env_id }}"
      Type: OSE_App
      Function: OpenShift
      kubernetes.io/cluster/c3ms: owned
    count: 1
    assign_public_ip: no
    image: "{{ ocp_ami }}"
    subnet_id: "{{ az_b_subnet_id }}"
    instance_type: "{{ node_instance_type }}"
    security_groups:
      - "{{ vpc_name }}-ocp-nodes"
      - "{{ default_security_group }}"
    iam_profile: "ocp-compute-node-iam-role"
    volumes:
      - "{{ base_volume }}"
      - device_name: /dev/sdd
        volume_size: 100
        delete_on_termination: yes
      - device_name: /dev/sde
        volume_size: 100
        delete_on_termination: yes

  - tags:
      Name: "{{ vpc_name }}-node-02"
      EnvID: "{{ env_id }}"
      Type: OSE_App
      Function: OpenShift
      kubernetes.io/cluster/c3ms: owned
    count: 1
    assign_public_ip: no
    image: "{{ ocp_ami }}"
    subnet_id: "{{ az_b_subnet_id }}"
    instance_type: "{{ node_instance_type }}"
    security_groups:
      - "{{ vpc_name }}-ocp-nodes"
      - "{{ default_security_group }}"
    iam_profile: "ocp-compute-node-iam-role"
    volumes:
      - "{{ base_volume }}"
      - device_name: /dev/sdd
        volume_size: 100
        delete_on_termination: yes
      - device_name: /dev/sde
        volume_size: 100
        delete_on_termination: yes

  - tags:
      Name: "{{ vpc_name }}-node-03"
      EnvID: "{{ env_id }}"
      Type: OSE_App
      Function: OpenShift
      kubernetes.io/cluster/c3ms: owned
    count: 1
    assign_public_ip: no
    image: "{{ ocp_ami }}"
    subnet_id: "{{ az_c_subnet_id }}"
    instance_type: "{{ node_instance_type }}"
    security_groups:
      - "{{ vpc_name }}-ocp-nodes"
      - "{{ default_security_group }}"
    iam_profile: "ocp-compute-node-iam-role"
    volumes:
      - "{{ base_volume }}"
      - device_name: /dev/sdd
        volume_size: 100
        delete_on_termination: yes
      - device_name: /dev/sde
        volume_size: 100
        delete_on_termination: yes

  - tags:
      Name: "{{ vpc_name }}-infra-01"
      EnvID: "{{ env_id }}"
      Type: OSE_Infra
      Function: OpenShift
      kubernetes.io/cluster/c3ms: owned
    count: 1
    assign_public_ip: no
    image: "{{ ocp_ami }}"
    subnet_id: "{{ az_b_subnet_id }}"
    instance_type: "{{ infra_instance_type }}"
    security_groups: 
      - "{{ vpc_name }}-ocp-infra"
      - "{{ default_security_group }}"
    iam_profile: "ocp-infra-node-iam-role"
    volumes:
      - "{{ base_volume }}"
      - device_name: /dev/sdd
        volume_size: 100
        delete_on_termination: yes
      - device_name: /dev/sde
        volume_size: 100
        delete_on_termination: yes

  - tags:
      Name: "{{ vpc_name }}-infra-02"
      EnvID: "{{ env_id }}"
      Type: OSE_Infra
      Function: OpenShift
      kubernetes.io/cluster/c3ms: owned
    count: 1
    assign_public_ip: no
    image: "{{ ocp_ami }}"
    subnet_id: "{{ az_b_subnet_id }}"
    instance_type: "{{ infra_instance_type }}"
    security_groups: 
      - "{{ vpc_name }}-ocp-infra"
      - "{{ default_security_group }}"
    iam_profile: "ocp-infra-node-iam-role"
    volumes:
      - "{{ base_volume }}"
      - device_name: /dev/sdd
        volume_size: 100
        delete_on_termination: yes
      - device_name: /dev/sde
        volume_size: 100
        delete_on_termination: yes

  - tags:
      Name: "{{ vpc_name }}-infra-03"
      EnvID: "{{ env_id }}"
      Type: OSE_Infra
      Function: OpenShift
      kubernetes.io/cluster/c3ms: owned
    count: 1
    subnet_id: "{{ az_c_subnet_id }}"
    assign_public_ip: no
    image: "{{ ocp_ami }}"
    instance_type: "{{ infra_instance_type }}"
    security_groups: 
      - "{{ vpc_name }}-ocp-infra"
      - "{{ default_security_group }}"
    iam_profile: "ocp-infra-node-iam-role"
    volumes:
      - "{{ base_volume }}"
      - device_name: /dev/sdd
        volume_size: 100
        delete_on_termination: yes
      - device_name: /dev/sde
        volume_size: 100
        delete_on_termination: yes

  - tags:
      Name: "{{ vpc_name }}-docker"
      EnvID: "{{ env_id }}"
      Type: Docker
    count: 1
    subnet_id: "{{ az_b_subnet_id }}"
    assign_public_ip: no
    image: "{{ ocp_ami }}"
    instance_type: m5.large
    security_groups: 
      - "{{ vpc_name }}-docker"
    volumes:
      - "{{ base_volume }}"
      - device_name: /dev/sdd
        volume_size: 100
        delete_on_termination: yes