user_home_dir: "{{ lookup('env', 'HOME') }}"
region: "{{ lookup('ini', 'region section=default file={{ user_home_dir }}/.aws/config') }}"
aws_access_key: "{{ lookup('ini', 'aws_access_key_id section=default file={{ user_home_dir }}/.aws/credentials') }}"
aws_secret_key: "{{ lookup('ini', 'aws_secret_access_key section=default file={{ user_home_dir }}/.aws/credentials') }}"
env_id:
vpc_name:
vpc_id:
az_b_subnet_id:
az_c_subnet_id:
ocp_ami:
master_instance_type: m5.xlarge
node_instance_type: m5.xlarge
infra_instance_type: m5.xlarge
default_security_group: "default"
key_name:
cidr: 10.0.0.0/16
bastion_hostname:
registry_hostname:
registry_pw:
default_iam: ""

