---
iam_policies:
  
  - name: "OCP-Compute-Node-IAM-Policy"
    description: Red Hat Compute Node IAM Policy
    policy:
      Version: '2012-10-17'
      Statement:
      - Action:
        - ec2:DescribeInstances
        Resource: "*"
        Effect: Allow
        Sid: '1'
    role_name: ocp-compute-node-iam-role
    service: ec2

  - name: "OCP-Bastion-IAM-Policy"
    description: Red Hat Bastion IAM Policy
    policy:
      Version: '2012-10-17'
      Statement:
      - Action:
        - ec2:DescribeVolume*
        - ec2:CreateVolume
        - ec2:CreateTags
        - ec2:DescribeInstances
        - ec2:AttachVolume
        - ec2:DetachVolume
        - ec2:DeleteVolume
        - ec2:DescribeSubnets
        - ec2:CreateSecurityGroup
        - ec2:DescribeSecurityGroups
        - ec2:DescribeRouteTables
        - ec2:AuthorizeSecurityGroupIngress
        - ec2:RevokeSecurityGroupIngress
        - elasticloadbalancing:DescribeInstanceHealth
        - elasticloadbalancing:DescribeTags
        - elasticloadbalancing:CreateLoadBalancerListeners
        - elasticloadbalancing:ConfigureHealthCheck
        - elasticloadbalancing:DeleteLoadBalancerListeners
        - elasticloadbalancing:RegisterInstancesWithLoadBalancer
        - elasticloadbalancing:DescribeLoadBalancers
        - elasticloadbalancing:CreateLoadBalancer
        - elasticloadbalancing:DeleteLoadBalancer
        - elasticloadbalancing:ModifyLoadBalancerAttributes
        - elasticloadbalancing:DescribeLoadBalancerAttributes
        Resource: "*"
        Effect: Allow
        Sid: '1'
    role_name: ocp-bastion-iam-role
    service: ec2

  - name: "OCP-Infra-Node-IAM-Policy"
    description: Red Hat Infra Node IAM Policy
    policy:
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Action:
        - s3:ListBucket
        - s3:GetBucketLocation
        - s3:ListBucketMultipartUploads
        Resource: arn:aws-us-gov:s3:::*
      - Effect: Allow
        Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
        - s3:ListMultipartUploadParts
        - s3:AbortMultipartUpload
        Resource: arn:aws-us-gov:s3:::*/*
      - Action:
        - ec2:DescribeInstances
        Resource: "*"
        Effect: Allow
        Sid: '1'
    role_name: ocp-infra-node-iam-role
    service: ec2

  - name: "OCP-Master-Node-IAM-Policy"
    description: Red Hat Master Node IAM Policy
    policy:
      Version: '2012-10-17'
      Statement:
      - Action:
        - ec2:DescribeVolume*
        - ec2:CreateVolume
        - ec2:CreateTags
        - ec2:DescribeInstances
        - ec2:AttachVolume
        - ec2:DetachVolume
        - ec2:DeleteVolume
        - ec2:DescribeSubnets
        - ec2:CreateSecurityGroup
        - ec2:DescribeSecurityGroups
        - ec2:DescribeRouteTables
        - ec2:AuthorizeSecurityGroupIngress
        - ec2:RevokeSecurityGroupIngress
        - elasticloadbalancing:DescribeInstanceHealth
        - elasticloadbalancing:DescribeTags
        - elasticloadbalancing:CreateLoadBalancerListeners
        - elasticloadbalancing:ConfigureHealthCheck
        - elasticloadbalancing:DeleteLoadBalancerListeners
        - elasticloadbalancing:RegisterInstancesWithLoadBalancer
        - elasticloadbalancing:DescribeLoadBalancers
        - elasticloadbalancing:CreateLoadBalancer
        - elasticloadbalancing:DeleteLoadBalancer
        - elasticloadbalancing:ModifyLoadBalancerAttributes
        - elasticloadbalancing:DescribeLoadBalancerAttributes
        Resource: "*"
        Effect: Allow
        Sid: '1'
    role_name: ocp-master-node-iam-role
    service: ec2