---
- name: Ensure that there's a line for the short host name and full hostname
  lineinfile:
    path: /etc/hosts
    regexp: "127.0.0.1"
    line: "127.0.0.1 {{ dns_config_hostname }}.{{ dns_config_domain }} {{ dns_config_hostname }} localhost localhost.localdomain localhost4 localhost4.localdomain4"
    state: present
  when: dns_config_localhost_in_etc_hosts
  
- name: Set the hostname of the machine
  hostname:
    name: "{{ dns_config_hostname }}.{{ dns_config_domain }}"
