---
- name: Install Required Packages
  include_tasks: packages.yml

- name: Configure Certificates
  include_tasks: certs.yml

- name: Add httpd content
  include_tasks: content.yml

- name: Configure httpd
  include_tasks: httpd.yml