---
- name: base-packages | Update all packages
  yum:
    name: '*'
    state: latest
    update_cache: true
  become: true

- name: base-packages | Install required packages
  yum:
    state: present
    name:
    - bash-completion
    - bind-utils
    - bridge-utils
    - docker
    - firewalld
    - git
    - iptables-services
    - kexec-tools
    - net-tools
    - openshift-ansible-{{ ocp_version }}
    - psacct
    - python2-boto3
    - sos
    - wget
    - yum-utils
  become: true
