---
- name: certificates-config | Create certificate and key files if using environment variables
  block:
  - name: certificates-config | Create certificate chain file for OCP Masters
    copy:
      content: "{{ ocp_masters_cert_chain }}"
      dest: /tmp/ocp_masters_chain.crt
      owner: root
      group: root
      mode: '0400'
    become: true

  - name: certificates-config | Create certificate key file for OCP Masters
    copy:
      content: "{{ ocp_masters_cert_key }}"
      dest: /tmp/ocp_masters.key
      owner: root
      group: root
      mode: '0400'
    become: true

  - name: certificates-config | Create certificate file for OCP Masters
    copy:
      content: "{{ ocp_masters_cert }}"
      dest: /tmp/ocp_masters.pem
      owner: root
      group: root
      mode: '0400'
    become: true

  - name: certificates-config | Create certificate chain file for OCP Apps
    copy:
      content: "{{ ocp_apps_cert_chain }}"
      dest: /tmp/ocp_apps_chain.crt
      owner: root
      group: root
      mode: '0400'
    become: true

  - name: certificates-config | Create certificate key file for OCP Apps
    copy:
      content: "{{ ocp_apps_cert_key }}"
      dest: /tmp/ocp_apps.key
      owner: root
      group: root
      mode: '0400'
    become: true

  - name: certificates-config | Create certificate file for OCP Apps
    copy:
      content: "{{ ocp_apps_cert }}"
      dest: /tmp/ocp_apps.pem
      owner: root
      group: root
      mode: '0400'
    become: true

  - name: certificates-config | Create certificate chain file for Keycloak
    copy:
      content: "{{ keycloak_cert_chain }}"
      dest: /tmp/keycloak_cert_chain.crt
      owner: root
      group: root
      mode: '0400'
    become: true
  when: ocp_masters_cert_chain|length > 0

- name: certificates-config | Copy certificate and key files from Ansible controller if not using environment variables
  block:
  - name: certificates-config | Create certificate chain file for OCP Masters
    copy:
      src: ocp-masters-chain.pem
      dest: /tmp/ocp_masters_chain.crt
      owner: root
      group: root
      mode: '0400'
    become: true

  - name: certificates-config | Create certificate key file for OCP Masters
    copy:
      src: ocp-masters-key.key
      dest: /tmp/ocp_masters.key
      owner: root
      group: root
      mode: '0400'
    become: true

  - name: certificates-config | Create certificate file for OCP Masters
    copy:
      src: ocp-masters-cert.pem
      dest: /tmp/ocp_masters.pem
      owner: root
      group: root
      mode: '0400'
    become: true

  - name: certificates-config | Create certificate chain file for OCP Apps
    copy:
      src: ocp-apps-chain.pem
      dest: /tmp/ocp_apps_chain.crt
      owner: root
      group: root
      mode: '0400'
    become: true

  - name: certificates-config | Create certificate key file for OCP Apps
    copy:
      src: ocp-apps-key.key
      dest: /tmp/ocp_apps.key
      owner: root
      group: root
      mode: '0400'
    become: true

  - name: certificates-config | Create certificate file for OCP Apps
    copy:
      src: ocp-apps-cert.pem
      dest: /tmp/ocp_apps.pem
      owner: root
      group: root
      mode: '0400'
    become: true

  - name: certificates-config | Create certificate chain file for Keycloak
    copy:
      src: keycloak-chain.pem
      dest: /tmp/keycloak_cert_chain.crt
      owner: root
      group: root
      mode: '0400'
    become: true
  when: ocp_masters_cert_chain|length == 0