---
- name: Build IAM policy
  iam_managed_policy:
    policy_name: "{{ item.name }}"
    policy_description: "{{ item.description }}"
    policy: "{{ item.policy | to_json }}"
    state: present
  loop: "{{ iam_policies }}"
  register: created_policy

- name: Attach IAM policy to a role
  iam_role:
    name: "{{ item.role_name }}"
    assume_role_policy_document: "{{ lookup('template','policy.json.j2') }}"
    managed_policy:
      - "{{ item.name }}"
    purge_policies: no
  loop: "{{ iam_policies }}"