---
- name: Provision Load Balancer
  elb_classic_lb:
    name: '{{ item.name }}'
    state: present
    scheme: '{{ item.scheme }}'
    region: '{{ region }}'
    security_group_names: '{{ item.security_groups }}'
    subnets: '{{ item.subnet }}'
    listeners: '{{ item.listeners }}'
    wait: true
    wait_timeout: 300
    health_check:
      ping_protocol: '{{ item.ping_protocol }}'
      ping_port: '{{ item.ping_port }}'
      ping_path: '{{ item.ping_path }}'
      response_timeout: '{{ item.response_timeout }}'
      interval: '{{ item.interval }}'
      unhealthy_threshold: '{{ item.unhealthy_threshold }}'
      healthy_threshold: '{{ item.healthy_threshold }}'
    tags:
      EnvID: '{{ vpc_name }}'
      Type: '{{ item.type }}'
  loop: '{{ elbs }}'
