---
# Tasks file for building security groups
- name: Build | Create Groups
  ec2_group:
    state: present
    name: "{{ item.group }}"
    description: "{{ item.description }}"
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    rules: "{{ item.rules_inbound }}"
    rules_egress: "{{ item.rules_outbound}}"
  loop: "{{ security_groups }}"
