---
- name: Destroy
  ec2_instance:
    state: terminated
    region: "{{ region }}"
    filters:
      "tag:EnvID": "{{ env_id }}"
      "tag:Type": "{{ item.type }}"
  loop: "{{ servers }}"
  register: ec2_results
