---
- name: Provision a set of instances
  ec2:
    region: '{{ region }}'
    instance_type: '{{ item.instance_type }}'
    image: '{{ item.image }}'
    tenancy: '{{ tenancy | default(omit) }}'
    assign_public_ip: '{{ item.assign_public_ip }}'
    vpc_subnet_id: '{{ item.subnet_id }}'
    volumes: '{{ item.volumes }}'
    groups: '{{ item.security_groups }}'
    instance_profile_name: '{{ item.iam_profile | default(default_iam) }}'
    key_name: '{{ key_name }}'
    wait: true
    instance_tags: "{{ item.tags }}"
    count_tag: "{{ item.tags }}"
    exact_count: '{{ item.count }}'
    termination_protection: '{{ item.termination_protection | default("no") }}'
  loop: '{{ servers }}'
  register: ec2_results
